# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 333cb53ec802ca564f1e95855c986d96986d7c03ea691d2b95705d4989e6a92fb4638b9887c4dc5214e66933958d1012e9940006903107e0f9e6418c114408e7

test:
  secret_key_base: a7281c17e2d90670cb5be71286c2539404ce0337fe2b7c79cb449446a1c334afd1e80b65d5a0c8c7480076c8ad8acecc9fa87552551bd99f662cc35fb585d537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
